### ISSUE TITLE
添加netflix的ip分流

### ISSUE THREAD

**Issue by 9bingyin** [jerrykuku/luci-app-vssr#106]
netflix电视端需要ip分流，否则无法观看

**Comment by 9bingyin** [comment]
> netflix电视端需要ip分流，否则无法观看

https://github.com/coolsnowwolf/lede/issues/3846

**Comment by jerrykuku** [comment]
哪个电视的客户端？

**Comment by jerrykuku** [comment]
我在sony tv 和firetv 上都可以完美的分流 没出现代理问题

**Comment by 9bingyin** [comment]
> 哪个电视的客户端？

google tv

**Comment by jerrykuku** [comment]
没有这个机型 理论和sony 的一样的 都是android tv os 的客户端

**Comment by jerrykuku** [comment]
今天更新了这个功能，但并没有实际测试，有时间的话可以测试下。

**Comment by 9bingyin** [comment]
GFW模式添加ip分流之后还是电视无法观看
ssr+插件的netflix分流可以正常观看

**Comment by jerrykuku** [comment]
gfw模式要搞ip  ip模式要搞域名。。。
迟早要Boom
