### ISSUE TITLE
请问能否将Socks5分离出来做为可选项

### ISSUE THREAD

**Issue by hplee0120** [jerrykuku/luci-app-vssr#109]
平常用不到，编译的时候希望能跟服务端一样能作为选择项，如果问题不大的话希望大佬考虑一下。

**Comment by jerrykuku** [comment]
socks5 不是能分离的功能 他只是v2ray 的一个自带功能而已。并不占用什么额外的空间

**Comment by hplee0120** [comment]
> socks5 不是能分离的功能 他只是v2ray 的一个自带功能而已。并不占用什么额外的空间

好的，谢谢解答。现在了解了。因为并不是因为空间纠结，单纯是有点强迫症不想要的服务不想让它出现，比如服务端那个就可以不加入，所以提问一下

**Comment by jerrykuku** [comment]
服务端 是可以选依赖 ssr-server 没有安装这个服务就不会显示。但是socks5 依赖v2ray 你v2ray 不装就没法玩了
