### ISSUE TITLE
不好意思，我又来了

### ISSUE THREAD

**Issue by lloyd18** [jerrykuku/luci-app-vssr#11]
期待出个只留V2ray的版本

不要SS -- 服务器容易被封
不要TORJAN--不是什么新技术 就是V2ray的 ws+tls换皮  不支持透明代理
不要服务端--我想这东西没几个人会用吧，真需要的话也有专门的插件
真的没必要什么都往里加，就像现在的手机浏览器，新闻也做，软件商店也做，天气也做，小说也做，短视频也做，结果啥也做不好。
其实也可以尝试做做减法，落后的技术就让它放进博物馆吧，重复造轮子的事就别参与了，专门去做好一件事就行了 V2ray那么多功能和协议真的够玩了

**Comment by jerrykuku** [comment]
v2ray 也有遗憾 upd 是over tcp 的 这样做游戏代理的时候 会导致nat 变差 。难完美

**Comment by lloyd18** [comment]
没有玩外服游戏，不是很了解，只是个人建议，最终取决于你。用vssr的主要原因就是觉得好看，可以适配你的argon主题。

**Comment by mianganing** [comment]
我玩PS4连机 V2RYA根本不能胜任还是要用到SS/SSR

**Comment by Hueysun** [comment]
我觉得服务端可以去掉

**Comment by jerrykuku** [comment]
> 没有玩外服游戏，不是很了解，只是个人建议，最终取决于你。用vssr的主要原因就是觉得好看，可以适配你的argon主题。

其实东西怎么做都难，做功能太多了，难免问题多。但是你没功能，广大网友的需求你懂的。可以没用不能没有。

**Comment by kyarazhan** [comment]
> > 没有玩外服游戏，不是很了解，只是个人建议，最终取决于你。用vssr的主要原因就是觉得好看，可以适配你的argon主题。
> 
> 其实东西怎么做都难，做功能太多了，难免问题多。但是你没功能，广大网友的需求你懂的。可以没用不能没有。

做人难！怎么做都有人说道！
