### ISSUE TITLE
lede/package/lean还是lede/package？

### ISSUE THREAD

**Issue by gcphym** [jerrykuku/luci-app-vssr#117]
请问为什么一定要放lede/package/lean？为什么其他好多插件都是放lede/package

**Comment by zhangj3** [comment]
楼上你在说啥？

ubuntu@ubuntu:~/lede/package$ ll
total 56
drwxrwxr-x  13 ubuntu ubuntu 4096 Jan 25 13:58 ./
drwxrwxr-x  18 ubuntu ubuntu 4096 Feb  1 15:17 ../
drwxrwxr-x   3 ubuntu ubuntu 4096 Jan 25 13:57 base-files/
drwxrwxr-x  31 ubuntu ubuntu 4096 Jan 25 13:57 boot/
drwxrwxr-x   8 ubuntu ubuntu 4096 Jan 25 13:57 devel/
drwxrwxr-x   8 ubuntu ubuntu 4096 Jan 26 10:13 feeds/
drwxrwxr-x  15 ubuntu ubuntu 4096 Jan 25 13:57 firmware/
drwxrwxr-x  28 ubuntu ubuntu 4096 Jan 25 13:57 kernel/
drwxrwxr-x 125 ubuntu ubuntu 4096 Feb  1 15:13 lean/
drwxrwxr-x  50 ubuntu ubuntu 4096 Jan 25 13:57 libs/
-rw-rw-r--   1 ubuntu ubuntu 4066 Jan 25 13:57 Makefile
drwxrwxr-x   6 ubuntu ubuntu 4096 Jan 25 13:57 network/
drwxrwxr-x  19 ubuntu ubuntu 4096 Jan 25 13:57 system/
drwxrwxr-x  30 ubuntu ubuntu 4096 Jan 25 13:57 utils/
-----------------------

ubuntu@ubuntu:~/lede/package/lean$ ls
adbyby               frp                        luci-app-cifsd          luci-app-music-remote-center  luci-app-ssrserver-python  luci-lib-fs          qt5                 UnblockNeteaseMusic
amule                gmediarender               luci-app-cifs-mount     luci-app-mwan3helper          luci-app-syncdial          luci-proto-bonding   r8125               UnblockNeteaseMusicGo
antileech            ipt2socks                  luci-app-cpufreq        luci-app-n2n_v2               luci-app-ttyd              luci-theme-argon     r8168               uugamebooster
autocore             ipv6-helper                luci-app-diskman        luci-app-netdata              luci-app-unblockmusic      luci-theme-netgear   rblibtorrent        v2ray
automount            k3-brcmfmac4366c-firmware  luci-app-dnsforwarder   luci-app-nfs                  luci-app-usb-printer       microsocks           rclone              v2ray-plugin
autosamba            k3screenctrl               luci-app-docker         luci-app-nft-qos              luci-app-uugamebooster     mt                   rclone-ng           verysync
baidupcs-web         kcptun                     luci-app-familycloud    luci-app-nps                  luci-app-v2ray-server      n2n_v2               rclone-webui-react  vlmcsd
coremark             libcryptopp                luci-app-filetransfer   luci-app-openvpn-server       luci-app-verysync          nft-qos              redsocks2           vsftpd-alt
csstidy              lua-maxminddb              luci-app-flowoffload    luci-app-pppoe-relay          luci-app-vlmcsd            npc                  samba4              wget
ddns-scripts_aliyun  luci-app-accesscontrol     luci-app-frpc           luci-app-ps3netsrv            luci-app-vsftpd            openwrt-fullconenat  shadowsocksr-libev  wol
ddns-scripts_dnspod  luci-app-adbyby-plus       luci-app-frps           luci-app-qbittorrent          luci-app-vssr              parted               shortcut-fe         wxbase
default-settings     luci-app-airplay2          luci-app-guest-wifi     luci-app-ramfree              luci-app-webadmin          pdnsd-alt            simple-obfs
dns2socks            luci-app-amule             luci-app-haproxy-tcp    luci-app-rclone               luci-app-wrtbwmon          polarssl             softethervpn5
dnsforwarder         luci-app-arpbind           luci-app-ipsec-vpnd     luci-app-samba4               luci-app-xlnetacc          proxychains-ng       srelay
dsmboot              luci-app-autoreboot        luci-app-jd-dailybonus  luci-app-sfe                  luci-app-zerotier          ps3netsrv            tcpping
fast-classifier      luci-app-baidupcs-web      luci-app-kodexplorer    luci-app-softethervpn         luci-lib-docker            qBittorrent          trojan

**Comment by jerrykuku** [comment]
放在哪里不是很重要
