### ISSUE TITLE
1.17之后的ipk无法使用套cf的节点

### ISSUE THREAD

**Issue by foogm** [jerrykuku/luci-app-vssr#118]
如题
同一节点，套用cf，换回1.17可用
1.20及1.22均不可用

**Comment by aoeg** [comment]
没有解决办法？弱鸡vps不套cf没法用，套了用不了1.22版helloworld

**Comment by jerrykuku** [comment]
我会看一下

**Comment by aoeg** [comment]
谢谢。其他节点，不用CDN加速的都可以用，套了就不行。
1.17.1及之前的都可以，1.20，1.22都不行。

**Comment by aoeg** [comment]
发现设置方式跟1.17之前不一样，host需要再ws设置外，还要在tls处设置。问题解决。
