### ISSUE TITLE
作者能否说一下，如何把你的小彩旗同时编译到lean大和ssrplus共存吗

### ISSUE THREAD

**Issue by norikohxb** [jerrykuku/luci-app-vssr#13]
作者能否说一下，如何把你的小彩旗同时编译到lean大和ssrplus共存吗

**Comment by norikohxb** [comment]
麻烦大大们辛苦一下直接弄成文件不冲突的，可以直接编译进去比较省事哈

**Comment by qxj** [comment]
把冲突的几个文件删掉就行了：
luci-app-vssr/root/etc/china_ssr.txt
luci-app-vssr/root/etc/config/black.txt
luci-app-vssr/root/etc/config/white.txt
luci-app-vssr/root/etc/dnsmasq.oversea/oversea_list.conf
luci-app-vssr/root/etc/dnsmasq.ssr/ad.conf
luci-app-vssr/root/etc/dnsmasq.ssr/gfw_base.conf

![](https://tva1.sinaimg.cn/large/00831rSTly1gcrigx0lguj31na0t612g.jpg)

**Comment by xpc0938** [comment]
我是把冲突的文件加入到了conffiles配置里面了, 编译就会通
##vim luci-app-vssr/Makefile
...
define Package/luci-app-vssr/conffiles
/etc/china_ssr.txt
/etc/dnsmasq.ssr/gfw_list.conf
/etc/dnsmasq.ssr/gfw_base.conf
/etc/dnsmasq.oversea/oversea_list.conf
endef
...

**Comment by jerrykuku** [comment]
> 我是把冲突的文件加入到了conffiles配置里面了, 编译就会通
> ##vim luci-app-vssr/Makefile
> ...
> define Package/luci-app-vssr/conffiles
> /etc/china_ssr.txt
> /etc/dnsmasq.ssr/gfw_list.conf
> /etc/dnsmasq.ssr/gfw_base.conf
> /etc/dnsmasq.oversea/oversea_list.conf
> endef
> ...

感谢提供

**Comment by fyngd** [comment]
> 我是把冲突的文件加入到了conffiles配置里面了, 编译就会通
> ##vim luci-app-vssr/Makefile
> ...
> define Package/luci-app-vssr/conffiles
> /etc/china_ssr.txt
> /etc/dnsmasq.ssr/gfw_list.conf
> /etc/dnsmasq.ssr/gfw_base.conf
> /etc/dnsmasq.oversea/oversea_list.conf
> endef
> ...

请问能说得详细点吗？新手村里出来的，conffiles 在哪个路径下？

**Comment by camino13** [comment]
> > 我是把冲突的文件加入到了conffiles配置里面了, 编译就会通
> > ##vim luci-app-vssr/Makefile
> > ...
> > define Package/luci-app-vssr/conffiles
> > /etc/china_ssr.txt
> > /etc/dnsmasq.ssr/gfw_list.conf
> > /etc/dnsmasq.ssr/gfw_base.conf
> > /etc/dnsmasq.oversea/oversea_list.conf
> > endef
> > ...
> 
> 请问能说得详细点吗？新手村里出来的，conffiles 在哪个路径下？

makefile里面，自己找下

**Comment by chinassr** [comment]
lean的ssr对于有些节点识别还是有点问题，会出现重复节点，昨天在群里问了说的订阅格式的原因，但vss和pass都没有出现重复节点的原因，唯独ssr其实这个问题一直存在，所以一直不用ssr用别的插件

**Comment by xpc0938** [comment]
> > 我是把冲突的文件加入到了conffiles配置里面了, 编译就会通
> > ##vim luci-app-vssr/Makefile
> > ...
> > define Package/luci-app-vssr/conffiles
> > /etc/china_ssr.txt
> > /etc/dnsmasq.ssr/gfw_list.conf
> > /etc/dnsmasq.ssr/gfw_base.conf
> > /etc/dnsmasq.oversea/oversea_list.conf
> > endef
> > ...
> 
> 请问能说得详细点吗？新手村里出来的，conffiles 在哪个路径下？

是在luci-app-vssr目录下的Makefile文件里面

**Comment by fyngd** [comment]
> > > 我是把冲突的文件加入到了conffiles配置里面了, 编译就会通
> > > ##vim luci-app-vssr/Makefile
> > > ...
> > > define Package/luci-app-vssr/conffiles
> > > /etc/china_ssr.txt
> > > /etc/dnsmasq.ssr/gfw_list.conf
> > > /etc/dnsmasq.ssr/gfw_base.conf
> > > /etc/dnsmasq.oversea/oversea_list.conf
> > > endef
> > > ...
> > 
> > 
> > 请问能说得详细点吗？新手村里出来的，conffiles 在哪个路径下？
> 
> makefile里面，自己找下

非常感谢，L大最新源码用这个方法好像失效了，有解决方法吗？

**Comment by fyngd** [comment]
> > > 我是把冲突的文件加入到了conffiles配置里面了, 编译就会通
> > > ##vim luci-app-vssr/Makefile
> > > ...
> > > define Package/luci-app-vssr/conffiles
> > > /etc/china_ssr.txt
> > > /etc/dnsmasq.ssr/gfw_list.conf
> > > /etc/dnsmasq.ssr/gfw_base.conf
> > > /etc/dnsmasq.oversea/oversea_list.conf
> > > endef
> > > ...
> > 
> > 
> > 请问能说得详细点吗？新手村里出来的，conffiles 在哪个路径下？
> 
> 是在luci-app-vssr目录下的Makefile文件里面

非常感谢，L大最新源码用这个方法好像失效了，有解决方法吗？

**Comment by jerrykuku** [comment]
已经可以同时编译
