### ISSUE TITLE
希望增加chinadns-ng

### ISSUE THREAD

**Issue by hplee0120** [jerrykuku/luci-app-vssr#135]
ssrp/vssr现有dns方案似乎无论是使用gfw模式或者大陆白名单模式，都是只有命中gfw列表的域名才会强制使用远程dns解析。但是实际情况是还有大量已经被污染但是未收录在gfw列表的域名。应该说现有方案跟gfw模式比较契合。但是跟大陆白名单模式不太契合。如果使用chinadns-ng跟大陆白名单模式配合，对于国内外分流应该比较准确 dns解析交给chinadns-ng判断  gfwlist中的域名直接远程解析，其他域名本地dns解析，如果解析出来的地址是国内的，则直接使用，如果是国外的，则用远程可信dns解析后走代理（现在passwall也已经默认开启使用chinadns-ng进行国内外分流了，还有新插件bypass），希望大佬有空可以考虑一下。

**Comment by aglent** [comment]
是的 如果能支持 更好
