### ISSUE TITLE
节点列表的🚩显示有误

### ISSUE THREAD

**Issue by ZerOri** [jerrykuku/luci-app-vssr#138]
除了香港和美国节点，其它国家地区全显示台湾的🚩，是我的节点订阅有问题还是控制面板识别出错了？

![QQ截图20210222152812](https://user-images.githubusercontent.com/46775615/108676270-eff3c400-7522-11eb-9896-0a0b060cdad6.png)
![QQ截图20210222153127](https://user-images.githubusercontent.com/46775615/108676378-144fa080-7523-11eb-87ed-902c366e4b9e.png)

**Comment by jerrykuku** [comment]
此问题在今天的提交中已经修复，只是暂时需要自行编译
