### ISSUE TITLE
请问 Koolshare 的 LEDE 支持么？

### ISSUE THREAD

**Issue by hidetag** [jerrykuku/luci-app-vssr#141]
Koolshare 的 LEDE 那堆依赖包什么的总感觉有点问题，每次一执行  opkg update 就会等很久，等很久不说更新完了就凉凉。。要么酷软中心打不开，要么其他服务用不了，我也是醉了。。所以不知道 这个用于 Lean 大 LEDE 的包用的了不..

**Comment by zh15933** [comment]
能用
![image](https://user-images.githubusercontent.com/32957590/109491628-c576ad80-7ac4-11eb-9a74-72840f01a41a.png)
