### ISSUE TITLE
小白求助ipk安装的一些问题

### ISSUE THREAD

**Issue by ZerOri** [jerrykuku/luci-app-vssr#145]
因为不会自行编译固件，暂时是通过opkg直接安装的，不过发现安装后分流和socks5功能不能用，不知道是不是因为插件需要的某些个依赖没有安装的缘故，如果是请告知插件所需依赖，如果不是纯粹是需要编译进固件才能使用的问题那就请关闭这个issue吧，感谢~
![QQ截图20210305121647](https://user-images.githubusercontent.com/46775615/110066552-b20d6000-7dac-11eb-9ce2-f591a116dee8.png)

**Comment by jerrykuku** [comment]
sock5依赖v2ray/xray 你看下系统是否有这两个

**Comment by jerrykuku** [comment]
另外左下角不能显示国旗icon 应该是没有安装 lua-maxminddb  在这里https://github.com/jerrykuku/luci-app-vssr/releases/tag/v1.08 选择一个安装下应该能解决

**Comment by ZerOri** [comment]
> sock5依赖v2ray/xray 你看下系统是否有这两个

好的，感谢，系统确实没装这两个，我安装下试试看

**Comment by ZerOri** [comment]
> 另外左下角不能显示国旗icon 应该是没有安装 lua-maxminddb 在这里https://github.com/jerrykuku/luci-app-vssr/releases/tag/v1.08 选择一个安装下应该能解决

哈哈，之前都没发现这个问题，安装完可以用了，非常感谢~

**Comment by ZerOri** [comment]
> sock5依赖v2ray/xray 你看下系统是否有这两个
v2ray有自带，但软件包里没找到xray 有下载链接吗？不知道用这个可不可以 https://github.com/yichya/openwrt-xray/releases

**Comment by jerrykuku** [comment]
什么硬件？

**Comment by ZerOri** [comment]
> 什么硬件？

极路由B70，MT7621

**Comment by jerrykuku** [comment]
![image](https://user-images.githubusercontent.com/9485680/110068134-ffd79780-7daf-11eb-85b9-d5c0856a2b7d.png)
试试这两个 不确定是哪一个

**Comment by ZerOri** [comment]
> ![image](https://user-images.githubusercontent.com/9485680/110068134-ffd79780-7daf-11eb-85b9-d5c0856a2b7d.png)
> 试试这两个 不确定是哪一个

成功了，服务全亮，非常感谢，不用编译固件真是太顶了
![QQ截图20210305125215](https://user-images.githubusercontent.com/46775615/110068915-aa9c8580-7db1-11eb-94fc-1f95131dc741.png)

**Comment by ZerOri** [comment]
> sock5依赖v2ray/xray 你看下系统是否有这两个

我又来叨扰了~卸载新固件的某个科学上网插件结果连v2ray模块都一并卸载了，请问hello world依赖的v2ray模块是哪个啊
