### ISSUE TITLE
东南亚国家节点识别出错？

### ISSUE THREAD

**Issue by ZerOri** [jerrykuku/luci-app-vssr#149]
![QQ截图20210308104751](https://user-images.githubusercontent.com/46775615/110270876-c5fdcf80-8001-11eb-98f0-ad6b3205adbf.png)

**RT，不知我这个是个例还是插件识别的bug，貌似订阅里的东南亚节点都会识别成CN**

**Comment by jerrykuku** [comment]
如果是中转节点 识别的节点ip 都是国内中转服务器的，旗帜的匹配规则是先匹配节点名称中的内容，比如是否包含常用的节点名称，如果没有则会使用ip来进行查询。你的两个节点是因为名称匹配脚本中不包含上述2国家。

**Comment by ZerOri** [comment]
> 如果是中转节点 识别的节点ip 都是国内中转服务器的，旗帜的匹配规则是先匹配节点名称中的内容，比如是否包含常用的节点名称，如果没有则会使用ip来进行查询。你的两个节点是因为名称匹配脚本中不包含上述2国家。
 
原来如此，谢谢解答，希望后续能添加。
