### ISSUE TITLE
编译警告并 失败

### ISSUE THREAD

**Issue by kyarazhan** [jerrykuku/luci-app-vssr#15]
WARNING: Makefile 'package/diy/luci-app-vssr/Makefile' has a dependency on 'lua-maxminddb', which does not exist

**Comment by jerrykuku** [comment]
git clone https://github.com/jerrykuku/lua-maxminddb.git  #git lua-maxminddb 依赖

git clone https://github.com/jerrykuku/luci-app-vssr.git

**Comment by tuughk** [comment]
我是也是  拉编译了  但是没有这个文件 maxminddb

**Comment by kyarazhan** [comment]
> git clone https://github.com/jerrykuku/lua-maxminddb.git #git lua-maxminddb 依赖
> 
> git clone https://github.com/jerrykuku/luci-app-vssr.git

这个是直接 git下来放在目录就行，还是必须勾选，还是啥的啊？

**Comment by jerrykuku** [comment]
放在那就行  vssr自动依赖

**Comment by kyarazhan** [comment]
问题已解决
