### ISSUE TITLE
ping所有节点功能无法使用，lua找不到地址

### ISSUE THREAD

**Issue by Xunflash** [jerrykuku/luci-app-vssr#155]
![image](https://user-images.githubusercontent.com/71567536/111312749-92bede80-869a-11eb-819e-5f413a9ae5bf.png)

![image](https://user-images.githubusercontent.com/71567536/111312810-a1a59100-869a-11eb-9fad-c16260e15eb7.png)

如图，500错误，点开目标地址后显示如图2

**Comment by jerrykuku** [comment]
安装 luasocket

**Comment by Xunflash** [comment]
> 安装 luasocket

感谢，已经解决
