### ISSUE TITLE
vssr 各项均显示 "未运行"

### ISSUE THREAD

**Issue by yukeiyang** [jerrykuku/luci-app-vssr#160]
原版 19.07.7, vssr 成功安装。节点也添加好了，但各项均显示 "未运行"。节点在  ssrplus 可成功运行，但在 vssr 始终不行。

**Comment by 0dulan0** [comment]
主题问题，我也是之前也是这样，换了个主题就好了

**Comment by yukeiyang** [comment]
@0dulan0 非常感谢，我试下。

**Comment by yukeiyang** [comment]
唯一的问题是，VSSR 目前仅支持OpenWrt 版本18, 也不支持原版，只对18版本的外部一种 theme 做了适配。我不太明白作者为何不为原版作适配。
