### ISSUE TITLE
vless://配置无法识别 

### ISSUE THREAD

**Issue by yege16888** [jerrykuku/luci-app-vssr#162]
xray 的vless配置链接 无法识别 提示无效格式（可手动配置）

输入无法识别的配置链接 提示无效格式后 依旧会添加一个空白的节点在列表里。（这应该也是个BUG吧。）

**Comment by jerrykuku** [comment]
因为没有适配

**Comment by yege16888** [comment]
导入错误 空白节点这个问题  也希望完善下。

**Comment by jerrykuku** [comment]
麻烦提供一个 配置连接的样例

**Comment by yege16888** [comment]
样例：vless://11e1dsf3-8bdb-432c-bccd-4ba0adsa5@xx.xxxx.net:443?encryption=none&security=xtls&ty1.net&headerType=none&flow=xtls-rprx-direct#xx.xxxx.net_VLESS_XTLS/TLS-direct_TCP

导入空白节点复现步骤：
导入配置信息—随意输入任意信息—确定（提示无效格式）—返回 查看节点列表 出现未命名空白节点。

**Comment by jerrykuku** [comment]
收到

**Comment by jerrykuku** [comment]
> 样例：vless://11e1dsf3-8bdb-432c-bccd-4ba0adsa5@xx.xxxx.net:443?encryption=none&security=xtls&ty1.net&headerType=none&flow=xtls-rprx-direct#xx.xxxx.net_VLESS_XTLS/TLS-direct_TCP
> 
> 导入空白节点复现步骤：
> 导入配置信息—随意输入任意信息—确定（提示无效格式）—返回 查看节点列表 出现未命名空白节点。

已经添加了vless 导入的支持。
