### ISSUE TITLE
显示当前节点的IP地址位置错误

### ISSUE THREAD

**Issue by 0dulan0** [jerrykuku/luci-app-vssr#166]
我用的节点是香港节点，119.*.*.* 但是启动之后下面的IP地址显示的是新加坡，我一直以为我这节点问题，我查了下我这个IP地址，结果多个查询工具查到的都是香港节点，所以应该是hw显示的是错误的

**Comment by Immity** [comment]
自带的ip库不一定完全正确，可以自定义，这不是啥大问题...

**Comment by realsteam** [comment]
我记得前几天更新过一次地址库，拉一版本最新的源码编译看看。

**Comment by jerrykuku** [comment]
更新过 geoip 库 而且由于库是免费库 所以无法保证完全准确
