### ISSUE TITLE
国内IP 和 GFW列表 无法正常使用,需要切换到全局才能正常使用 

### ISSUE THREAD

**Issue by Klosw** [jerrykuku/luci-app-vssr#176]
使用V2ray节点 运行模式选择 绕过国内IP 和 GFW列表 无法访问 google ,但是使用全局模式就能使用 .
我之前以为是加入了IPV6导致的,但是编译一个不带IPV6的似乎情况差不多 
我不太清楚是什么问题 有啥解决办法吗 

Vssr 集成了  Xray  Trojan 
SS|SSR|Xray|Trojan 
 

**插件版本:**
 - Openwrt版本 ImmortalWrt 18.06 branch (git-21.108.65328-b655412)
 - 主题以及版本 ArgonTheme v1.7.2 
 - 插件版本 1.22-1-20210322

**Comment by z826540272** [comment]
同样,xray用不了.

**Comment by Klosw** [comment]
> 同样，xray用不了。

我换成了 V2ray 就好用了 换成了 1.22 版本了 然后没有 加入 Xray

**Comment by Klosw** [comment]
> 同样，xray用不了。

我最近又编译了一个发现可以用了
