### ISSUE TITLE
Vssr 编译失败缺少依赖

### ISSUE THREAD

**Issue by MedyMa** [jerrykuku/luci-app-vssr#179]
**描述Bug**

由于lean源码更新删除了shadowsocksr-libev，编译时是缺少shadowsocksr-libev-alt、shadowsocksr-libev-server依赖

**截图**
![image](https://user-images.githubusercontent.com/75345465/117903145-9ae57400-b301-11eb-9e4b-b9dc35d6dccc.png)

**Comment by 19901019** [comment]
编译前输入rm -rf tmp && ./scripts/feeds install -f -p helloworld shadowsocksr-libev
