### ISSUE TITLE
编译完成安装opwrt后无法进入web管理页面？

### ISSUE THREAD

**Issue by gzjacktang** [jerrykuku/luci-app-vssr#185]
Lean大 openwrt，编译过程没问题。但是opwrt 安装后第一进管理页面就会出现以下问题
/usr/lib/lua/luci/ccache.lua:70: error loading module 'luci.controller.vssr' from file '/usr/lib/lua/luci/controller/vssr.lua':
	/usr/lib/lua/luci/controller/vssr.lua:317: 'end' expected (to close 'function' at line 5) near '<eof>'
stack traceback:
	[C]: in function 'loader'
	/usr/lib/lua/luci/ccache.lua:70: in function </usr/lib/lua/luci/ccache.lua:61>
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:526: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:553: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:238: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

SSH进去修改主题也没用，但是卸载本apk后就没用任何问题直接进入web管理页面
apk 版本 luci-app-vssr - 1.22-2-20210512

**Comment by weigeloveu** [comment]
一样的问题

**Comment by dqylyln** [comment]
一样问题，看样子像是没测试，/usr/lib/lua/luci/controller/vssr.lua 函数没闭合，缺少end。 直接ssh 到op，vi方式在317行添加end 后界面恢复正常，但是页面的“客户端”，“游戏模式”，“pdnsd”，“socket” 全部无法开启。

**Comment by dqylyln** [comment]
已经卸载ipk的方式，卸载掉问题版本luci-app-vssr_1.22-2-20210512，重新安装luci-app-vssr_1.22-20210227 的ipk 后恢复正常。

**Comment by mzl0408** [comment]
同样的问题，编译了好几遍都一样，后来把vssr取消了，结果好了，不知道是哪个源码的问题。

**Comment by jerrykuku** [comment]
这个问题应该在周末的时候修复了，目前还有问题的 还是这个提示么？

**Comment by dqylyln** [comment]
> 这个问题应该在周末的时候修复了，目前还有问题的 还是这个提示么？

刚才试了下，确实恢复可以了，不在报vssr.lua的错误了，但是要注意，通过ipk 方式覆盖安装，会导致之前配置的节点等信息丢失，需要重新手工在配置一次。

**Comment by mzl0408** [comment]
> 这个问题应该在周末的时候修复了，目前还有问题的 还是这个提示么？

晚上回去编译再看看

**Comment by gzjacktang** [comment]
> 这个问题应该在周末的时候修复了，目前还有问题的 还是这个提示么？

晚点试试 看评论应该是修复叻。

**Comment by mzl0408** [comment]
> 问题

刚刚编译完了，没问题了
