### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by 19188** [jerrykuku/luci-app-vssr#187]
最新lean源码按照readme编译结果
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-vssr:
 * 	shadowsocksr-libev-ssr-local
 * 	shadowsocksr-libev-ssr-redir
 * 	shadowsocksr-libev-ssr-check
 * 	xray-core
 * 	xray-plugin
 * 	shadowsocksr-libev-ssr-server
 * opkg_install_cmd: Cannot install package luci-app-vssr.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/zero/lede'
make[1]: *** [package/Makefile:108: /home/zero/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/zero/lede'
make: *** [/home/zero/lede/include/toplevel.mk:224: world] Error 2

**Comment by cleviry** [comment]
按照这个#114   可以解决依赖问题
可以参考我的解决步骤
```bash
# 1.清除缓存
rm -rf tmp
# 2.feeds.conf文件添加源
src-git helloworld https://github.com/fw876/helloworld
src-git passwall https://github.com/xiaorouji/openwrt-passwall
# 3.重新执行升级安装下载编译等操作
./scripts/feeds update -a
./scripts/feeds install -a
make -j8 download V=s
make -j1 V=s
```
