### ISSUE TITLE
感觉很卡，保存&应用要30s

### ISSUE THREAD

**Issue by lloyd18** [jerrykuku/luci-app-vssr#19]
RTRTRT

**Comment by jerrykuku** [comment]
你这r2s吧

**Comment by lloyd18** [comment]
> 你这r2s吧

J1900的CPU

**Comment by jerrykuku** [comment]
麻烦报上 openwrt版本 luci 版本 是谁的源 另外我这是luci-app 保存的逻辑来自于openwrt luci 本身 ，正常情况下是不应该超过8秒的

**Comment by lloyd18** [comment]
> 麻烦报上 openwrt版本 luci 版本 是谁的源 另外我这是luci-app 保存的逻辑来自于openwrt luci 本身 ，正常情况下是不应该超过8秒的

重新编译了一次，还是一样，用秒表记着刚好30秒，还有就是sock5默认状态是运行中，但sock5设置里并未勾选启用

**Comment by jerrykuku** [comment]
你是不是编译了lean的 v2ray服务器？ x86的我们很多人在用 并没有保存慢的问题

**Comment by lloyd18** [comment]
> 你是不是编译了lean的 v2ray服务器？ x86的我们很多人在用 并没有保存慢的问题

没有编译v2ray服务器，不知道是不是只有我一个人这样，如果源码没问题我再排除一下吧，不过确实是上次源码更新才出这种情况

**Comment by jerrykuku** [comment]
不过上一次源码 确实修改了 socks5的一些代码 我也看下

**Comment by lloyd18** [comment]
> 不过上一次源码 确实修改了 socks5的一些代码 我也看下
> 不过我在pi zero plus上测试过，没有任何问题。开机不会自动运行socks5
> 我这边 保存应用的时间 是 6秒 左右。 你自己进ssh 然后 执行 /etc/init.d/vssr restart 自己 看看 要执行多久

 /etc/init.d/vssr restart要28秒 取消所有插件 仅编译vssr还是这样 刷完机第一次打开vssr sock5是运行状态 取消后重启路由器后不会自动运行

**Comment by lloyd18** [comment]
你的源码应该没问题 因为我刷回之前编译的版本也是这样
