### ISSUE TITLE
插件跟主题好像有挺多不兼容现象

### ISSUE THREAD

**Issue by hplee0120** [jerrykuku/luci-app-vssr#2]
除了argon主题比较正常外，不过这个主题本身不大完美。试用了其他几个主题都不大正常，表现为保存并订阅节点无效，国旗图标不显示，还有下面的网站检测错位。
电脑端谷歌输入法

**Comment by jerrykuku** [comment]
本来就是搭配argon 使用的

**Comment by jerrykuku** [comment]
尝试修改主题 把主题中的jquery 从footer里 转移到 header 中试试看
