### ISSUE TITLE
运行一段时间后，会出现出墙访问ok，墙内网站加载失败或者加载明显拖慢。

### ISSUE THREAD

**Issue by binlkevin** [jerrykuku/luci-app-vssr#206]
如题，本人最近转为使用helloworld。分流确实很方便。openwrt作为主路由使用，桥接光猫负责拨号。运行一段时间后，会出现翻墙一切正常，但访问墙内服务会出现链接失败。加载微信或者打开淘宝京东都失败的现象。然后发现重新提交一次hello world后又能恢复。
使用饶过大陆ip模式，x86版本openwrt。使用物理机安装op，并没有使用虚拟机和其他系统共存，也未开启任何其他翻墙插件，也未运行例如smartdns一类工具。

**Comment by jerrykuku** [comment]
出问题时用ip111.con 看下 ip情况，目前我自己在用未出现过类似问题，如果再出问题 可以先测下ip 然后再来反馈

**Comment by binlkevin** [comment]
> 出问题时用ip111.con 看下 ip情况，目前我自己在用未出现过类似问题，如果再出问题 可以先测下ip 然后再来反馈

OK

**Comment by binlkevin** [comment]
从国内测试
123.x.x.x 中国 xx市

这是您访问国内网站所使用的IP

从国外测试
64.x.x.x x国 xxx

您访问没有被封的国外网站所使用的IP

从谷歌测试
64.x.x.x x国 xxx

这是您访问谷歌，Facebook，Twitter等网站所使用的IP

此时微信和一些国内app都无法联网，但Netflix正常播放

**Comment by binlkevin** [comment]
重刷新版固件好像又恢复了。也许不是hello world的问题。请关闭这个issue吧。

**Comment by wayne0926** [comment]
> 从国内测试 123.x.x.x 中国 xx市
> 
> 这是您访问国内网站所使用的IP
> 
> 从国外测试 64.x.x.x x国 xxx
> 
> 您访问没有被封的国外网站所使用的IP
> 
> 从谷歌测试 64.x.x.x x国 xxx
> 
> 这是您访问谷歌，Facebook，Twitter等网站所使用的IP
> 
> 此时微信和一些国内app都无法联网，但Netflix正常播放

我连ip111都上不去了
