### ISSUE TITLE
提个建议，新建节点的国家，应该改为“国家或地区”

### ISSUE THREAD

**Issue by newsfancolaice** [jerrykuku/luci-app-vssr#21]
![image](https://user-images.githubusercontent.com/22072533/75794191-685df400-5dab-11ea-8890-927a85cd808f.png)

如上图所示，如果添加的服务器是港澳台地区，成为国家是不合适的，望采纳。

**Comment by garypang13** [comment]
非常合适,这本来就是用来对抗恶政的工具,没必要自我审查,

**Comment by Zilanbo** [comment]
> ![image](https://user-images.githubusercontent.com/22072533/75794191-685df400-5dab-11ea-8890-927a85cd808f.png)
> 
> 如上图所示，如果添加的服务器是港澳台地区，成为国家是不合适的，望采纳。
自我审查习惯了？看见hk被标注为国家就玻璃心
