### ISSUE TITLE
opewrt master 中文界面问题

### ISSUE THREAD

**Issue by ksong008** [jerrykuku/luci-app-vssr#213]
openwrt 为master版本，vssr最新版，主菜单没有完整转换成中文

![1631673474(1)](https://user-images.githubusercontent.com/54489832/133361294-d9ed1418-cd38-4006-ad84-53cf7eb4ffd8.jpg)

**Comment by ksong008** [comment]
应该是我自己的问题

**Comment by VergilGao** [comment]
请问一下你这边解决了吗？我电脑上显示的没有完全汉化，但是手机访问页面都是中文的。
