### ISSUE TITLE
PDNS问题

### ISSUE THREAD

**Issue by lauren12133** [jerrykuku/luci-app-vssr#217]
openwrt版本：19.07 内核4.9    vssr版本：最新    问题：vssr运行一段时间过后  会出现无法正常链接外网的问题 检查发现是PDNSD的问题，是否尝试加入其他的dns模式 如dns2socks和Xray-tcp和xray-doh

**Comment by VergilGao** [comment]
我的建议是用smartdns

**Comment by lauren12133** [comment]
不喜欢外挂dns，而且smartdns并没有你想象中那么好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jerrykuku/luci-app-vssr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 上午9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jerrykuku/luci-app-vssr] PDNS问题 (Issue #217)





 
我的建议是用smartdns
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VergilGao** [comment]
我用了两年多smartdns了，没发现哪里有问题。
我选这个库就是不喜欢那种非得把所有功能都集成起来的库。

**Comment by Neverends4** [comment]
确实，不喜欢smartdns那种访问一个网站就要把访问记录朝全部DNS服务器撒一遍的做法
不过现在有选本机#5335的选项，你可以在本机开个socks代理，然后装https-dns-proxy之类用代理访问DNS
