### ISSUE TITLE
苍狼国内IP库 识别不够准确

### ISSUE THREAD

**Issue by v03413** [jerrykuku/luci-app-vssr#220]
**描述Bug**
苍狼的大陆IP库不够准确，会导致部分腾讯轻量新加坡网段43.155.x.x 依旧识别为大陆IP；导致在选择绕过大陆IP模式的时候依旧是直连，速度堪忧；如果可以，希望作者增加一个更为精准的可选项 https://github.com/Hackl0us/GeoIP2-CN ，优化体验。

**插件版本:**
 - Openwrt版本  `OpenWrt R21.12.1 / LuCI Master (git-21.329.83689-00cb491)`
 - 插件版本 `v1.22`

**Comment by jerrykuku** [comment]
会考虑 近期更新一下
