### ISSUE TITLE
让指定内网IP走代理

### ISSUE THREAD

**Issue by Chasenx** [jerrykuku/luci-app-vssr#223]
家里建了一个 Samba 服务，同时也建立 SS 代理，在外面用 Clash 全局走这个 SS 代理是可以用 Samba 的。
现在想要实现的是在学校宿舍的软路由中，使用 HelloWorld 设置一个分流规则，让特定IP段（192.168.50.0/24）走这个 SS 代理。之前尝试将 IP 段添加到自定义规则里面，但发现不能使用，想问下是不是需要改对应 iptables 的规则。

**Comment by jerrykuku** [comment]
是的 需要把局域网某个ip的所有流量都转发到指定节点的代理服务。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月11日(周二) 晚上8:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jerrykuku/luci-app-vssr] 让指定内网IP走代理 (Issue #223)




 
家里建了一个 Samba 服务，同时也建立 SS 代理，在外面用 Clash 全局走这个 SS 代理是可以用 Samba 的。
 现在想要实现的是在学校宿舍的软路由中，使用 HelloWorld 设置一个分流规则，让特定IP段（192.168.50.0/24）走这个 SS 代理。之前尝试将 IP 段添加到自定义规则里面，但发现不能使用，想问下是不是需要改对应 iptables 的规则。

**Comment by Chasenx** [comment]
> 是的 需要把局域网某个ip的所有流量都转发到指定节点的代理服务。
> […](#)

想问下具体应该修改 iptables 中的哪条规则或者哪条链，之前看了一下 iptables 的内容，发现里面真的太多了，不知道该如何下手

**Comment by Chasenx** [comment]
- 解决了，我把 */usr/bin/vssr-rules* 里面的 *192.168.0.0/16* 都替换成 *192.168.1.0/24*，只过滤本地的 IP 段，然后在自定义列表那里添加 *192.168.50.0/24*
