### ISSUE TITLE
请问可以加一个viu代理的设置吗

### ISSUE THREAD

**Issue by ws115** [jerrykuku/luci-app-vssr#23]
https://www.viu.com/ 这个网站，我看视频比较多，但是香港阿里云的速度比较慢，不想当主服务器，谢谢

**Comment by jerrykuku** [comment]
最近工作忙 稍后补上

**Comment by jerrykuku** [comment]
已经可以自定义全部分流节点

**Comment by HIPIEPIE** [comment]
你好，请问viu分流的域名可以给一份吗？万分感谢。
我就设置了viu.com分流，现在网页可以正常访问，iOS app和apple tv app都无法访问，不清楚是怎么回事。
