### ISSUE TITLE
台湾视频服务代理不包括台湾爱奇艺啊

### ISSUE THREAD

**Issue by ws115** [jerrykuku/luci-app-vssr#24]
试了一下台湾爱奇艺没有效果，要把主服务器设为台湾节点，然后代理域名写上cache.m.iqiyi.com
video.iqiyi.com 才有用，麻烦改一下，让台湾视频代理支持台湾爱奇艺，谢谢楼主了

**Comment by jerrykuku** [comment]
可以在自定义分流实现

**Comment by 778bbq** [comment]
> 可以在自定义分流实现

怎么操作
