### ISSUE TITLE
白名单域名，黑名单域名列表 没生效

### ISSUE THREAD

**Issue by chika0801** [jerrykuku/luci-app-vssr#244]
**描述Bug**
我编译出来是英文的。
在图上菜单中Bypass是白名单（域名不走代理）。
Black是黑名单，强行走代理的意思吧）。

**复现过程**
请描述如何复现错误:
1将域名ispip.clang.cn放在白名单里，我在VPS上禁止了此域名，VPS上会阻止访问。

3在网页上点“保存并应用”，“保存” ，关闭节点，重新开节点，确认规则生效。

2网页浏览器打不开此网址，更新IP列表失败，VPS的LOG上看到此域名来访问，被阻止了。证明白名单没生效。

**截图**
![1](https://user-images.githubusercontent.com/88967758/163574247-ffa3f9da-9d42-424d-a0e8-38bef40f00f4.jpg)

**插件版本:**
 -  ImmortalWrt 5.15.31
ImoutoWrt SNAPSHOT r22260-296bb7ed4e / LuCI Master git-22.092.46871-703113c

 - 主题以及版本
agron ArgonTheme v2.2.9
 - 插件版本
 4月15日最新源码编译的

**桌面系统信息:**
 - 系统和版本
 - 浏览器类型以及
 - 版本

**手机系统信息:**
 - 设备类型：【例如 Iphone x】
 - 系统和版本
 - 浏览器类型
 - 版本

**补充说明**
任何补充请在这里叙述.

**Comment by v03413** [comment]
针对你的复现过程，大概率判断是**终端DNS缓存**问题   

---  
## 为什么会出现这种情况呢？
白名单黑名单功能表面是依靠域名，本质上也是依赖IP进行分流；dnsmasq 对应两个配置文件 `whitelist_forward.conf blacklist_forward.conf`，也分别对应的是 ipset 里面的`whitelist blacklist`。  

在你保存应用之后，对应的dnsmasq配置文件发生变化，但此时如果dnsmasq没有收到对应域名的dns请求，则ipset对应的黑白名单不会发生变化，随之则是分流无效，表象就是 黑名名单没生效。

## 那我们应该如何避免这种情况呢？

1. 使用任何可用的方法，清空终端设备的dns 缓存。
2. 路由器执行、命令 `nslookup xxxxx.com(你的域名)`，强制刷新一遍dns缓存。

**Comment by chika0801** [comment]
感谢你的解答。
