### ISSUE TITLE
 luci-app-vssr 编译完成没有菜单！

### ISSUE THREAD

**Issue by lbbboy** [jerrykuku/luci-app-vssr#264]
是不是 ssr-plus 和这个一起要选上？

**Comment by zhdot** [comment]
哥们你的编译成功了吗？我的是硬路由ea8500按照说明里的方法  lean源码 编译完没有错误  但是没法进入新刷入的系统  会重启到之前的系统 不知道怎么回事

**Comment by lbbboy** [comment]
> 哥们你的编译成功了吗？我的是硬路由ea8500按照说明里的方法 lean源码 编译完没有错误 但是没法进入新刷入的系统 会重启到之前的系统 不知道怎么回事

解决了

**Comment by zhdot** [comment]
> > 哥们到你们的编译成功了吗？是我路由硬ea8500按照说明里的精益编译完成没有错误但是无法进入新刷入的系统会重启之前的系统不知道怎么自己
> 
> 解决了
能给说一下 编译的完整教程吗   或者要注意的点   谢谢

**Comment by lbbboy** [comment]
> > > 哥们到你们的编译成功了吗？是我路由硬ea8500按照说明里的精益编译完成没有错误但是无法进入新刷入的系统会重启之前的系统不知道怎么自己
> > 
> > 
> > 解决了
> > 能给说一下 编译的完整教程吗   或者要注意的点   谢谢

硬路由啊，格式化分区后在写入吧。

**Comment by zhdot** [comment]
> > > > 哥们到你们的编译成功了吗？是我路由硬ea8500按照说明里的精益编译完成没有错误但是无法进入新刷入的系统会重启之前的系统不知道怎么自己
> > > 
> > > 
> > > 解决了
> > > 能给说一下 编译的完整教程吗   或者要注意的点   谢谢
> 
> 硬路由啊，格式化分区后在写入吧。

额  好吧

**Comment by lbbboy** [comment]
我用的是云编译，
```
feeds

sed -i '$a src-git helloworld https://github.com/fw876/helloworld' feeds.conf.default
sed -i '$a src-git passwall https://github.com/xiaorouji/openwrt-passwall' feeds.conf.default

# lua-maxminddb
git clone https://github.com/jerrykuku/lua-maxminddb.git package/lean/lua-maxminddb

# luci-app-vssr
git clone https://github.com/jerrykuku/luci-app-vssr.git package/lean/luci-app-vssr

```

**Comment by zhdot** [comment]
> 我用的是云编译，
> 
> ```
> feeds
> 
> sed -i '$a src-git helloworld https://github.com/fw876/helloworld' feeds.conf.default
> sed -i '$a src-git passwall https://github.com/xiaorouji/openwrt-passwall' feeds.conf.default
> 
> # lua-maxminddb
> git clone https://github.com/jerrykuku/lua-maxminddb.git package/lean/lua-maxminddb
> 
> # luci-app-vssr
> git clone https://github.com/jerrykuku/luci-app-vssr.git package/lean/luci-app-vssr
> 
> 然后
> scripts/feeds update -a
> scripts/feeds install -a
> make menuconfig
> ```

好的 我研究研究试试

**Comment by zhdot** [comment]
> 我用的是云编译，
> 
> ```
> cd lede/package/lean/
> feeds
> 
> sed -i '$a src-git helloworld https://github.com/fw876/helloworld' feeds.conf.default
> sed -i '$a src-git passwall https://github.com/xiaorouji/openwrt-passwall' feeds.conf.default
> 
> cd ~/lede
> # lua-maxminddb
> git clone https://github.com/jerrykuku/lua-maxminddb.git package/lean/lua-maxminddb
> 
> # luci-app-vssr
> git clone https://github.com/jerrykuku/luci-app-vssr.git package/lean/luci-app-vssr
> 
> 然后
> scripts/feeds update -a
> scripts/feeds install -a
> make menuconfig
> ```

你的是ssrp+vssr的吗？

**Comment by lbbboy** [comment]
```
https://github.com/kenzok8/small-package

cd lede
sed -i '$a src-git small8 https://github.com/kenzok8/small-package‘ feeds.conf.default

scripts/feeds update -a
scripts/feeds install -a
make menuconfig
```
用这个吧，这个还有 市场。
应用市场 luci-app-store

**Comment by zhdot** [comment]
> ```
> https://github.com/kenzok8/small-package
> 
> cd lede
> sed -i '$a src-git small8 https://github.com/kenzok8/small-package‘ feeds.conf.default
> 
> scripts/feeds update -a
> scripts/feeds install -a
> make menuconfig
> ```
> 
> 用这个吧，这个还有 市场。 应用市场 luci-app-store 不用那么多步骤，这个包里面包含上面全部vssr 所需要的依赖。

好的 谢谢啦

**Comment by lbbboy** [comment]
> https://github.com/kenzok8/small-package

错了个上标号  ’ 自己改下
