### ISSUE TITLE
作者你好 现在ssr可以和vssr同时编译吗？

### ISSUE THREAD

**Issue by qq1316237299** [jerrykuku/luci-app-vssr#27]
作者你好 现在ssr可以和vssr同时编译吗？或者有什么办法可以同时编译吗？

**Comment by fyngd** [comment]
希望老大能解决不能与ssrp+同时编译的问题。

**Comment by jerrykuku** [comment]
https://github.com/jerrykuku/luci-app-vssr/issues/13#issuecomment-611872801

参考这个 在  luci-app-vssr/makefile 下。
抱歉最近很忙 所以暂时没有时间维护更新。

**Comment by qq1316237299** [comment]
> [#13 (comment)](https://github.com/jerrykuku/luci-app-vssr/issues/13#issuecomment-611872801)
> 
> 参考这个 在 luci-app-vssr/makefile 下。
> 抱歉最近很忙 所以暂时没有时间维护更新。

感谢作者，我现在编译上去了  很舒服

**Comment by qq1316237299** [comment]
> > [#13 (comment)](https://github.com/jerrykuku/luci-app-vssr/issues/13#issuecomment-611872801)
> > 参考这个 在 luci-app-vssr/makefile 下。
> > 抱歉最近很忙 所以暂时没有时间维护更新。
> 
> 感谢作者，我现在编译上去了 很舒服

把错误的文件都删掉就好了
