### ISSUE TITLE
最近运行vssr，都是全局翻墙状态，无论是GFW模式还是白名单

### ISSUE THREAD

**Issue by lisankai93** [jerrykuku/luci-app-vssr#270]
**描述Bug**
最近运行vssr，都是全局翻墙，无论是GFW模式还是白名单

**复现过程**
请描述如何复现错误r:
SSR节点到期，因此自己搭了xray梯子，然后最近运行都是默认全局代理，尝试过重启路由器、替换大陆ip白名单，都没用

**截图**
百度查询ip都是海外ip

**插件版本:**
 - Openwrt版本：OpenWrt R22.4.1 / LuCI Master (git-22.091.36880-c3be048) ，5.15.32内核，自编译
 - 主题以及版本
 - 插件版本：Xray 1.5.4 (Xray, Penetrates Everything.) OpenWrt (go1.17.8 linux/amd64) （日志获取）

另外看了issue里面有个帖子自己更新了大陆ip段30万行那个，也都没用（在etc/vssr里面直接替换原来的china_ssr.txt，是这么换没错吧？）

以及我看到如果自己手动替换了这个txt，订阅更新是又回到8000多行的大陆ip段，如何解决呢？（自己cronbat手动每天替换吗？）

谢谢！

**Comment by lisankai93** [comment]
已通过下载ipk更新到最新版本，问题依旧。更新过程貌似还有点bug，如下


root@OpenWrt:/mnt/sda3# opkg install lua-maxminddb_0.2-1_x86_64.ipk
Package lua-maxminddb (0.2-1) installed in root is up to date.
root@OpenWrt:/mnt/sda3# opkg install luci-app-vssr_1.24-20220421_all.ipk
Upgrading luci-app-vssr on root from 1.23-20220108 to 1.24-20220421...
stop
Removing obsolete file /usr/share/rpcd/acl.d/luci-app-vssr.json.
Configuring luci-app-vssr.
ipset v7.15: The set with the given name does not exist
* 05/24 16:37:20| pdnsd: info: pdnsd-1.2.9b-par starting.
* 05/24 16:37:20| pdnsd: warning: EOF encountered while reading entry count from                              disk cache file.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/vssr/white.list is different from the conffile in the new package. The new conffile will be placed at /etc/vssr/white.list-opkg.
 * resolve_conffiles: Existing conffile /etc/vssr/gfw_list.conf is different from the conffile in the new package. The new conffile will be placed at /etc/vssr/gfw_list.conf-opkg.
 * resolve_conffiles: Existing conffile /etc/vssr/china_ssr.txt is different from the conffile in the new package. The new conffile will be placed at /etc/vssr/china_ssr.txt-opkg.
 * resolve_conffiles: Existing conffile /etc/vssr/black.list is different from the conffile in the new package. The new conffile will be placed at /etc/vssr/black.list-opkg.
 * resolve_conffiles: Existing conffile /etc/config/vssr is different from the conffile in the new package. The new conffile will be placed at /etc/config/vssr-opkg.

**Comment by lisankai93** [comment]
以及更新后，在高级设置里面，填入国内IP段来源地址然后保存&应用后，
下面【国内IP段】这一项依旧是8628条记录

**Comment by v03413** [comment]
你的问题描述过于玄学... 如果一点没效果，建议看看openwrt 防火墙分流规则是否存在，关键词`SS_SPEC_WAN_AC`

**Comment by lisankai93** [comment]
是在这里看么？我这个有问题吗？谢谢大佬

root@OpenWrt:/tmp/etc# cat vssr.include
#!/bin/sh
iptables-save -c | grep -v "SS_SPEC" | iptables-restore -c
iptables-restore -n <<-EOT
*nat
:SS_SPEC_WAN_AC - [0:0]
:SS_SPEC_WAN_FW - [0:0]
-I PREROUTING 1 -p tcp -m set --match-set ss_spec_lan_ac src -m comment --comment _SS_SPEC_RULE_ -j SS_SPEC_WAN_AC
-I OUTPUT 1 -p tcp -m comment --comment _SS_SPEC_RULE_ -j SS_SPEC_WAN_AC
-A SS_SPEC_WAN_AC -m set --match-set whitelist dst -j RETURN
-A SS_SPEC_WAN_AC -m set --match-set blacklist dst -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_AC -m set --match-set fplan src -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_AC -d 107.174.176.22/32 -p tcp -m tcp ! --dport 53 -j RETURN
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_ac dst -j RETURN
-A SS_SPEC_WAN_AC -m set --match-set gmlan src -m set ! --match-set china dst -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_AC -m set --match-set china dst -j RETURN
-A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_FW -d 0.0.0.0/8 -j RETURN
-A SS_SPEC_WAN_FW -d 10.0.0.0/8 -j RETURN
-A SS_SPEC_WAN_FW -d 127.0.0.0/8 -j RETURN
-A SS_SPEC_WAN_FW -d 169.254.0.0/16 -j RETURN
-A SS_SPEC_WAN_FW -d 172.16.0.0/12 -j RETURN
-A SS_SPEC_WAN_FW -d 192.168.0.0/16 -j RETURN
-A SS_SPEC_WAN_FW -d 224.0.0.0/4 -j RETURN
-A SS_SPEC_WAN_FW -d 240.0.0.0/4 -j RETURN
-A SS_SPEC_WAN_FW -p tcp -m multiport --dports 22,53,587,465,995,993,143,80,443,9418 -j REDIRECT --to-ports 1234
COMMIT
*mangle
COMMIT
EOT

**Comment by lisankai93** [comment]
用ssr也一样，重新编译重新刷机试试了，目前就先不打扰大佬了
