### ISSUE TITLE
使用lienol的openwrt，编译混后运行trojan 提升客户端未运行

### ISSUE THREAD

**Issue by lsq726** [jerrykuku/luci-app-vssr#284]
git clone lienol 源码

cd lienol/package/
git clone https://github.com/jerrykuku/lua-maxminddb.git #git lua-maxminddb 依赖 
git clone https://github.com/jerrykuku/luci-app-vssr.git

feeds.conf文件添加源 src-git helloworld https://github.com/fw876/helloworld src-git passwall https://github.com/xiaorouji/openwrt-passwall

mkdir -p package/helloworld for i in "dns2socks" "microsocks" "ipt2socks" "pdnsd-alt" "redsocks2"; do \ svn checkout "https://github.com/immortalwrt/packages/trunk/net/$i" "package/helloworld/$i"; \ done

 make menuconfig

make download 
 make -j1 V=s

是我操作哪不对还是其他？

**Comment by 286700234** [comment]
lienol 和lede的源码问题都是一样的，插件的问题，用ssr和password的都没有这个问题

**Comment by lsq726** [comment]
> 题

这插件只能用官方的源码么？

**Comment by lsq726** [comment]
竭神 能解决一下么?是我们编译的方法有问题还是 需要竭神 修正?

**Comment by lsq726** [comment]
原来helloworld客户端是能运行...
trojan 协议 需要等待比较久才能运行.
