### ISSUE TITLE
修改makefile后还是不能和lean的ssr plus一起编译

### ISSUE THREAD

**Issue by Sunnice** [jerrykuku/luci-app-vssr#29]
Collected errors:
 * check_data_file_clashes: Package luci-app-ssr-plus wants to install file /home/sunnice/openwrt/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/etc/dnsmasq.oversea/oversea_list.conf
	But that file is already provided by package  * luci-app-vssr
 * check_data_file_clashes: Package luci-app-ssr-plus wants to install file /home/sunnice/openwrt/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/etc/dnsmasq.ssr/gfw_base.conf
	But that file is already provided by package  * luci-app-vssr
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.

**Comment by camino13** [comment]
把luci-app-vssr/root/etc/dnsmasq.oversea/oversea_list.conf和etc/dnsmasq.ssr/gfw_base.conf这两文件删除了应该就能编译过了！！

**Comment by Sunnice** [comment]
> 把luci-app-vssr/root/etc/dnsmasq.oversea/oversea_list.conf和etc/dnsmasq.ssr/gfw_base.conf这两文件删除了应该就能编译过了

**Comment by Sunnice** [comment]
> 把luci-app-vssr/root/etc/dnsmasq.oversea/oversea_list.conf和etc/dnsmasq.ssr/gfw_base.conf这两文件删除了应该就能编译过了！！

我试试
