### ISSUE TITLE
其实你可以把你的项目 Pull requests给lean大，一起维护！

### ISSUE THREAD

**Issue by snakwu** [jerrykuku/luci-app-vssr#3]
其实你可以把你的项目 Pull requests给lean大，一起维护！

**Comment by jerrykuku** [comment]
目前项目受局限于argon主题 无法通用 再看看吧

**Comment by snakwu** [comment]
嗯，应该lean还是比较欢迎大家一起维护项目的，坐等Pull requests，谢谢这么好的项目

**Comment by hplee0120** [comment]
牛逼plus，如果将这些图标用到lean的plus+上肯定很多人喜欢。

**Comment by kyarazhan** [comment]
> 牛逼plus，如果将这些图标用到lean的plus+上肯定很多人喜欢。魔改版那个实在是太花哨了，而且设置项也比较繁杂，菜单也会多出几个隧道和dns什么的插件，
我看够呛，除非有性能上的提升，花里胡哨不是路由器主要实现的功能，不能本末倒置

**Comment by jerrykuku** [comment]
> 牛逼plus，如果将这些图标用到lean的plus+上肯定很多人喜欢。魔改版那个实在是太花哨了，而且设置项也比较繁杂，菜单也会多出几个隧道和dns什么的插件，

本来就是基于ssr+的修改 适度做了精简 提高操作效率 唯一的缺点就是 文件体积大了不少。

**Comment by jerrykuku** [comment]
> > 牛逼plus，如果将这些图标用到lean的plus+上肯定很多人喜欢。魔改版那个实在是太花哨了，而且设置项也比较繁杂，菜单也会多出几个隧道和dns什么的插件，
> > 我看够呛，除非有性能上的提升，花里胡哨不是路由器主要实现的功能，不能本末倒置

花哨不会影响性能 只会牺牲容量而已 视觉增强不是本末倒置

**Comment by snakwu** [comment]
支持,v2ray plus,还有可以增加自定义解释dns,支持dnsforwarder,这些其实都是性能的得升,其实,真的可以Pull requests给lean,通不通过再说

**Comment by snakwu** [comment]
好的项目大家一起维护,lean本身一个人维护,也顾全不了那么多

**Comment by hplee0120** [comment]
如果说到功能，那可以考虑增加obfs支持或者自定义dns应该挺好

**Comment by jerrykuku** [comment]
> 如果说到功能，那可以考虑增加obfs支持或者自定义dns应该挺好
ss simple obfs 早期支持 后来去掉ss 就不再支持了 可以试试 ss+v2ray plugin   可以来到我的tg群 
https://t.me/PIN1Group 欢迎来讨论

**Comment by snakwu** [comment]
> > 如果说到功能，那可以考虑增加obfs支持或者自定义dns应该挺好
> > ss simple obfs 早期支持 后来去掉ss 就不再支持了 可以试试 ss+v2ray plugin   可以来到我的tg群
> > https://t.me/PIN1Group 欢迎来讨论

希望可以解决一下主题问题,然后Pull requests给lean

**Comment by kyarazhan** [comment]
> 如果说到功能，那可以考虑增加obfs支持或者自定义dns应该挺好

这个问题，大雕上个月已经在QQ群里说过了，dns解析，默认的设置就挺好，暂时没有其它优化方案。我实际操作smartdns、AG，最后还是回到了大雕的默认方案，当然这也是我的技术比较水的原因。pull给lean，还是要给个一揽子的解决方案。大雕也在群里说过要美化ssr-plus，但大家一致认为稳定、性能才是主要的，后面事情如何发展就不知道了。

**Comment by jerrykuku** [comment]
> > 如果说到功能，那可以考虑增加obfs支持或者自定义dns应该挺好
> 
> 这个问题，大雕上个月已经在QQ群里说过了，dns解析，默认的设置就挺好，暂时没有其它优化方案。我实际操作smartdns、AG，最后还是回到了大雕的默认方案，当然这也是我的技术比较水的原因。pull给lean，还是要给个一揽子的解决方案。大雕也在群里说过要美化ssr-plus，但大家一致认为稳定、性能才是主要的，后面事情如何发展就不知道了。

我目前使用也是当前的方案还是比较稳定的。美化这个问题 不会影响稳定性，也不会影响性能。除了占用空间  没有其他的负面影响。

**Comment by hplee0120** [comment]
> > > 如果说到功能，那可以考虑增加obfs支持或者自定义dns应该挺好
> > 
> > 
> > 这个问题，大雕上个月已经在QQ群里说过了，dns解析，默认的设置就挺好，暂时没有其它优化方案。我实际操作smartdns、AG，最后还是回到了大雕的默认方案，当然这也是我的技术比较水的原因。pull给lean，还是要给个一揽子的解决方案。大雕也在群里说过要美化ssr-plus，但大家一致认为稳定、性能才是主要的，后面事情如何发展就不知道了。
> 
> 我目前使用也是当前的方案还是比较稳定的。美化这个问题 不会影响稳定性，也不会影响性能。除了占用空间 没有其他的负面影响。

ssr+这段时间以来基本已经没看见有啥新拓展方向了，按照目前的情况看来可以说是比较趋于稳定完美了，我比较赞同在原有基础上可以搞搞美化，比如这个国旗。锦上添花。并不属于本末倒置。比如很多东西，手表或是手机种种软件或硬件，第一要素肯定是内部需要稳定和性能支撑，内部做好了可以在表面再下些功夫。可以加不少分。比如那句科技以换壳为本哈哈。

**Comment by coolsnowwolf** [comment]
我也赞成，前端是我的弱项~

**Comment by jerrykuku** [comment]
> 我也赞成，前端是我的弱项~

之前不是私聊过你。只是很多前端代码乱七八糟，最近在整理前端代码。差不多了的话 其实可以很方便的的移植到ssr+

**Comment by qq1316237299** [comment]
支持ssr加入美化
