### ISSUE TITLE
有3个订阅链接，设置自动更新，第2天看一个节也没有了，3个订阅链接全变成一样的了

### ISSUE THREAD

**Issue by modelsun** [jerrykuku/luci-app-vssr#303]
**描述Bug**
请清晰的描述bug

**复现过程**
请描述如何复现错误r:

**截图**
如果可以尽可能的上传错误的截图

**插件版本:**
 - Openwrt版本 ：ImmortalWrt luci 18.06
 - 主题以及版本
 - 插件版本 

**桌面系统信息:**
 - 系统和版本
 - 浏览器类型以及
 - 版本

**手机系统信息:**
 - 设备类型：【例如 Iphone x】
 - 系统和版本
 - 浏览器类型
 - 版本

**补充说明**
任何补充请在这里叙述.

同时还有  ssr p+,和pw，会有冲突吗？

**Comment by yocus** [comment]
我也反馈一下这个情况吧。
R2S，刷的DHDAXCW骷髅头的固件，即2022.09.19 NanoPi-R2S-linux-5.4_正式版_全插件(openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz)
版本信息如下：
Powered by LuCI Master (git-22.190.06436-4a8cc2a) https://github.com/openwrt/luci
[ArgonTheme v1.7.3] https://github.com/jerrykuku/luci-theme-argon 
OpenWrt R22.9.15 (2022-09-19)
固件自带的服务里就有Hello World这个服务，所以直接用了，因为是小白，所以这个插件的版本号信息不知道怎么查看。
使用是很简单也很方便，尤其是Netflix分流，简单的配置就搞定，对我这样的小白用户来说很友好。
简单说下遇到的这个问题吧。
自建了一个服务器节点A，使用1号机场的订阅可以得到CDE三个节点，一共是4个节点(1个自建3个机场订阅出来的)。
在基本设置中，把A节点设置为主服务器，开启分流后，把C节点设置为Netflix代理，保存应用，可以正常使用。
但如果在订阅设置中开启自动更新，那么自动更新以后，基本设置中的配置就很可能发生变化，具体表现是：主服务器的节点变成了CDE其中一个而不是A，而Netflix代理节点也可能是CDE其中一个。
因为A节点的IP地址协议什么的都是固定不便的，也不是订阅出来的节点，既然已经设置为了主服务器，那是否应该无论订阅的节点怎么更新都保持这个A节点作为主服务器不变，除非手动设置。
CDE三个节点是从机场订阅更新出来的，每次更新后虽然名称都是一样的，但IP和协议可能会有差异，那么这个时候能否根据节点的名称来固定在分流设置中，这样就不会每次更新后基本设置中的节点就发生各种变化。

另外，节点列表中的大部分节点可以ping出延迟速度，但自建的节点其实是可以使用的，速度还很快，就是Ping就显示Error，好比在手机上用小火箭测延迟，用TCP就是不通，但改用ICMP就Ok。所以，“节点列表”这里是否能进行一下调整。
还有就是，这个国家和地区以及对应的国旗图标显示非常不准确，手动设置后，订阅节点只要更新，虽然节点名称还是一样的，但图标显示就又出现各种错误了，不得不放弃修改，这个不影响使用，但看起来确实别扭，不知道能否做出调整，比如显示一样的图标，或者干脆不要显示图标。


以上就是我遇到的问题，做一个反馈，希望能得到回复。
最后还是非常感谢各位大佬开发出这么实用的神器。
非常感谢。

**Comment by jerrykuku** [comment]
不建议开启自动更新，会影响分流策略。 节点的速度不是ping 是使用的socket链接的速度， 列表中的国旗识别策略是，优先从节点名称中进行匹配 英文简称->国家->最后使用IP库进行识别。  底部的国旗的策略是直接使用最终IP从IP库直接进行查询。

**Comment by yocus** [comment]
具体版本刚才看到了：luci-app-vssr | 1.25-20220423

**Comment by yocus** [comment]
感谢回复，还是希望主服务器这一项如果设置为非订阅获取的节点时，能强制固定。
因为很多用户使用的都是各种机场订阅，而进入10月，机场也在不停的更新调整节点，每次手动更新再配置确实会麻烦。
而其他一些插件使用相对复杂，而Hello World是对小白用户最为友好的。
非常感谢，持续支持~

**Comment by modelsun** [comment]
谢谢解答

**Comment by yocus** [comment]
有3个订阅链接，设置自动更新，第2天看一个节也没有了，3个订阅链接全变成一样的了 #303

标题描述的这个问题确实存在，我使用了四个机场订阅连接，无任何规律，但概率比较高的会出现标题所说的问题，其中一个订阅连接总是提示获取订阅列表为空，但实际上是有节点的，“保存并开始订阅”多次问题依旧，希望开发者留意一下这个问题。
