### ISSUE TITLE
openwrt原版引入了ujail，导致vssr注册的dnsmasq配置无法读取

### ISSUE THREAD

**Issue by bingyuxq** [jerrykuku/luci-app-vssr#305]
![20221018091505](https://user-images.githubusercontent.com/11748396/196312568-acf552f8-cf59-4e72-88cb-e4e247759fb3.png)
/tmp/dnsmasq.ssr配置文件无法被读取，openwrt22.03的dnsmasq现在通过jail启动，如果启动时jail未挂载文件夹将无法访问，即使文件就在那放着。
建议直接patch一下dnsmasq的启动脚本，增加mount配置文件的部分，或者直接将配置文件写到/tmp/dnsmasq.d这个默认会挂载上去的目录里。
![image](https://user-images.githubusercontent.com/11748396/196312919-0fab2522-948a-462e-b6b8-ec8674830768.png)

**Comment by zonyitoo** [comment]
可以不用patch dnsmasq的脚本，上面它有mount `$dnsmasqconfdir`，这个一般来讲就是 `/tmp/dnsmasq.d` 。ssrplus插件就是用这个的

```
$ ls /tmp/dnsmasq.d
dnsmasq-ssrplus.conf  dnsmasq-ssrplus.d
```

小改一下就好
