### ISSUE TITLE
自定义端口有没有合并到以前需要代理的端口里面？

### ISSUE THREAD

**Issue by 286700234** [jerrykuku/luci-app-vssr#306]
需要代理的端口选项这里其实可以把自定义端口给合并在一起，这样就可以不同的人的需求去不同的设置

**Comment by zyren** [comment]
是的，另外即便自定义代理端口，也不支持IP段设置，比如0-10000，这样填入没有任何作用

**Comment by Koukotsukan** [comment]
> 是的，另外即便自定义代理端口，也不支持IP段设置，比如0-10000，这样填入没有任何作用， 这样防止BT走代理的话，需要写很多个端口号进去，很不现实呀

端口范围应该是使用冒号，例如0:65535

**Comment by zyren** [comment]
> > 是的，另外即便自定义代理端口，也不支持IP段设置，比如0-10000，这样填入没有任何作用， 这样防止BT走代理的话，需要写很多个端口号进去，很不现实呀
> 
> 端口范围应该是使用冒号，例如0:65535

感谢解答，解决了我的大困惑
