### ISSUE TITLE
更新后的hello world和SSR Plus同时编译仍然又冲突

### ISSUE THREAD

**Issue by minfengyk** [jerrykuku/luci-app-vssr#31]
今天看到jerrykuku大佬更新代码，解决冲突问题。立刻用Lean大的源码，hello world和SSR Plus同时编译，仍然有冲突。还是按#13 (comment)的方法，删除相关文件才编译通过。

**Comment by fyngd** [comment]
一样，看到大佬已经把相关文件添加了，但是还是不能同时编译。只能删除以下冲突文件。
lede/package/lean/luci-app-vssr/root/etc/china_ssr.txt
lede/package/lean/luci-app-vssr/root/etc/dnsmasq.oversea
lede/package/lean/luci-app-vssr/root/etc/dnsmasq.ssr/gfw_base.conf
lede/package/lean/luci-app-vssr/root/etc/dnsmasq.ssr/gfw_list.conf

**Comment by jerrykuku** [comment]
冲突问题 暂时无法解决
