### ISSUE TITLE
您好，想请问下要怎么设置才能给PS4用

### ISSUE THREAD

**Issue by z19960413** [jerrykuku/luci-app-vssr#33]
想问下helloworld里，首页中，游戏模式UDP中继服务器  这个选项如果要选的话，是不是需要配置UDP2raw或者UDPspeeder才会生效？
然后我想给我的PS4设置代理，访问控制这一栏应该怎么填？
我之前用的是koolshare lede，装的v2插件，PS4上测试网络，白名单模式一般下行80-90Mbps，现在用helloworld，不管我访问控制填不填，怎么填，都是十几Mbps，甚至个位数。
想请教下应该怎么设置

**Comment by jerrykuku** [comment]
抱歉 我没有ps4 测试不了
