### ISSUE TITLE
请问可以增加ChinaDNS-NG吗

### ISSUE THREAD

**Issue by yubanmeiqin9048** [jerrykuku/luci-app-vssr#36]

**Comment by jerrykuku** [comment]
需要研究一下，个人认为pdnsd已经足够用了

**Comment by yubanmeiqin9048** [comment]
私以为，CHINADNS NG的DNS劫持是个有意思的功能，相对PDNSD我感觉也好用些，hello目前界面做得很漂亮，适当加上一些新功能也是不错的

**Comment by jerrykuku** [comment]
有时间来研究一下

**Comment by garypang13** [comment]
ChinaDNS-NG是在本地解析到域名,没必要加.

**Comment by yubanmeiqin9048** [comment]
> ChinaDNS-NG是在本地解析到域名,没必要加.

行吧，在用dnscrypt-proxy2

**Comment by hplee0120** [comment]
建议增加ChinaDNS-NG实现更准确的国内外分流，现有方案似乎无论是gfw模式或者大陆白名单模式都是采用只有命中gfw列表才会强制发往远程dns解析。但是实际情况还有大量未收录在gfw列表的国外域名，应该说现有方案比较契合使用gfw模式，大陆白名单还是跟ChinaDNS-NG配合比较合理
