### ISSUE TITLE
为什么节点状态显示都是ERROR？

### ISSUE THREAD

**Issue by dayunliang** [jerrykuku/luci-app-vssr#38]
本应节点正常显示PING值的地方都是显示ERROR，是为何？
![Jietu20200516-075859](https://user-images.githubusercontent.com/36461319/82104979-936da800-974b-11ea-8c8e-299d4d225594.jpg)

**Comment by dayunliang** [comment]
但是偶尔有一个节点又会显示明显不正常的PING值数

![Jietu20200516-080434](https://user-images.githubusercontent.com/36461319/82105090-0f67f000-974c-11ea-8ea2-3df867256dee.jpg)

**Comment by jerrykuku** [comment]
这个不是ping值 而是使用socket 连接的 时间长。

**Comment by dayunliang** [comment]
为什么都是ERROR呢？如何解决？

**Comment by dayunliang** [comment]
> 这个不是ping值 而是使用socket 连接的 时间长。

为什么都是ERROR呢？ 该如何解决？

**Comment by shu0802** [comment]
![image](https://user-images.githubusercontent.com/43750373/95029195-28604600-06d9-11eb-89c7-0da90484f78c.png)
在哪里打开？
