### ISSUE TITLE
国旗只显示联合国

### ISSUE THREAD

**Issue by Be27f** [jerrykuku/luci-app-vssr#4]
节点有美日港台英徳新等不同地区， 但全显示联合国
请问是漏了什么没有配置么？

**Comment by jerrykuku** [comment]
目前识别国旗就两种方式  先用节点名称  检查节点名称中是否包含 emoji iso code 没有再检查ip iplc 都是国内ip 为了显示美观 所以用了联合国，另外麻烦能不能把截图去掉？

**Comment by Be27f** [comment]
fix bugs

@jerrykuku
jerrykuku committed yesterday
 
Update getflag.sh

@jerrykuku
jerrykuku committed yesterday
