### ISSUE TITLE
点击订阅按钮没有反应

### ISSUE THREAD

**Issue by lbh0123** [jerrykuku/luci-app-vssr#40]
作者你好，我编译lean最新的固件，添加了hello world，在使用订阅的时候点击订阅按钮 没有任何反应，请问是何故啊

**Comment by jerrykuku** [comment]
请搭配argon主题使用

**Comment by yjw8336** [comment]
f12发现这个是缺少jquery.min.js，
1.ssh登录路由，输入命令 : curl http://code.jquery.com/jquery-1.4.1.min.js >> /www/luci-static/bootstrap/js/jquery.min.js
（如果报js 目录不存在就创建下，命令为：mkdir  /www/luci-static/bootstrap/js/ ）

2.在 /usr/lib/lua/luci/view/vssrupdate_subscribe.htm 文件的第三行增加<script src="/luci-static/bootstrap/js/jquery.min.js"></script>
刷新页面就好

**Comment by lbh0123** [comment]
> f12发现这个是缺少jquery.min.js，
> 1.ssh登录路由，输入命令 : curl http://code.jquery.com/jquery-1.4.1.min.js >> /www/luci-static/bootstrap/js/jquery.min.js
> （如果报js 目录不存在就创建下，命令为：mkdir /www/luci-static/bootstrap/js/ ）
> 
> 2.在 /usr/lib/lua/luci/view/vssrupdate_subscribe.htm 文件的第三行增加<script src="/luci-static/bootstrap/js/jquery.min.js"></script>
> 刷新页面就好

感谢帮助，我去重新编译后再尝试一下

**Comment by lbh0123** [comment]
> 请搭配argon主题使用

谢谢作者回复，等等我去试一试
