### ISSUE TITLE
开启helloworld后，ddns解析的域名端口转发后无法访问任何

### ISSUE THREAD

**Issue by yufeiyang2008** [jerrykuku/luci-app-vssr#43]
大佬，不知道是固件的问题还是helloworld的问题，请了解，开启helloworld后，ddns解析的域名访问不了，端口转发没有问题，关闭helloworld后恢复正常

**Comment by jerrykuku** [comment]
无法访问的时候 ping一下自己的域名，对比自己的公网ip 看下

**Comment by yufeiyang2008** [comment]
感谢大佬热心回复，问题找到了，是ddns解析的问题，解析地址和wan地址不一致
