### ISSUE TITLE
为什么vssr.include被修改后，重启后又恢复到修改之前的。急！

### ISSUE THREAD

**Issue by matthuo333** [jerrykuku/luci-app-vssr#45]
如题，是在哪里flush了么？

**Comment by jerrykuku** [comment]
这个文件在什么地方？

**Comment by matthuo333** [comment]
在 /var/etc/
我的openwrt版本：
Linux MT-OP 3.14.29 #1 SMP Tue May 28 17:32:37 CST 2019 aarch64 GNU/Linux

**Comment by jerrykuku** [comment]
这个目录是在内存中的 重启后肯定会复位。

**Comment by matthuo333** [comment]
> 这个目录是在内存中的 重启后肯定会复位。

哦，求大神告知如果修改此文件内容，是在哪里修改呢？

因为其中内容有条规则影响我当前设置。

**Comment by jerrykuku** [comment]
/usr/bin/vssr-rules  应该在这里

**Comment by matthuo333** [comment]
> /usr/bin/vssr-rules  应该在这里

那看起来要重新修改再编译了?

**Comment by jerrykuku** [comment]
你直接去修改这个文件即可

**Comment by matthuo333** [comment]
在这个文件中插入下面这个后：
flush_r && fw_rule && ipset_r && ac_rule && tp_rule && gen_include
/usr/sbin/iptables-restore < /root/ipmt.fw
iptables -t nat -D PREROUTING 1
iptables -t nat -I PREROUTING 5 -p tcp -m comment --comment _SS_SPEC_RULE_ -j SS_SPEC_WAN_AC
[ "$?" = 0 ] || loger 3 "Start failed!"
exit $?

重启，查询 NAT表后，总是被下面第一条替换，总是把新增的规则冲掉。

SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */

希望预期增加的规则：

iptables -t nat -I PREROUTING  1  -m mac --mac-source xx:xx:xx:xx  -j SS_SPEC_WAN_AC
iptables -t nat -I PREROUTING  2  -m mac --mac-source xx:xx:xx:xx -j ACCEPT
iptables -t nat -I PREROUTING  3  -m mac --mac-source xx:xx:xx:xx -j ACCEPT
iptables -t nat -I PREROUTING  4  -m mac --mac-source xx:xx:xx:xx -j ACCEPT
iptables -t nat -I PREROUTING  5   -p tcp    -j DNAT --to 127.0.0.1:xxxxx

**Comment by matthuo333** [comment]
还请大神再给看看

**Comment by matthuo333** [comment]
最后屏蔽了下面两条相关restore, 就OK了， 但是这两条的作用是？屏蔽了会有什么问题？
gen_include() {
        [ -n "$FWI" ] || return 0
        extract_rules() {
                echo "*$1"
                iptables-save -t $1 | grep SS_SPEC_ |\
                        sed -e "s/^-A \(OUTPUT\|PREROUTING\)/-I \1 1/"
                echo 'COMMIT'
        }
        cat <<-EOF >>$FWI
#       iptables-save -c | grep -v "SS_SPEC" | iptables-restore -c
#       iptables-restore -n <<-EOT
        $(extract_rules nat)
        $(extract_rules mangle)
        EOT
EOF
        return 0
}
