### ISSUE TITLE
希望能搞一个自定义分流功能，例如某些域名/IP走固定的代理

### ISSUE THREAD

**Issue by Margular** [jerrykuku/luci-app-vssr#46]

**Comment by Yofo-me** [comment]
对，赞成

**Comment by BraveSail** [comment]
![image](https://user-images.githubusercontent.com/49320262/88287002-477b4880-cd24-11ea-8105-40b6ae3cb351.png)
这里要是能自定义就行

**Comment by SUNNY-CT** [comment]
赞同  现在在局域网LAN里  只能指定某些IP不走代理   我是合租  家里接入的设备太多了，希望能指定只有某些局域网IP走代理

**Comment by jerrykuku** [comment]
自定义分流已经实现

**Comment by SUNNY-CT** [comment]
> 自定义分流已经实现

大佬牛X
