### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by EnnawYang** [jerrykuku/luci-app-vssr#5]
建议文件内容再稍微修改下，可以与lean或者其他人的共存，比如passwall可以和ssr+共存，同时编译进去，刚刚试着编译了一下有几个文件和ssr+冲突了所以导致编译失败，涉及到的文件：
``/etc/china_ssr.txt
/etc/config/black.list
/etc/config/gfw.list
/etc/config/white.list
/etc/dnsmasq.oversea/oversea_list.conf
/etc/dnsmasq.ssr/ad.conf
/etc/dnsmasq.ssr/gfw_base.conf``

**Comment by jerrykuku** [comment]
会尝试修改 谢谢

**Comment by kyarazhan** [comment]
> 建议文件内容再稍微修改下，可以与lean或者其他人的共存，比如passwall可以和ssr+共存，同时编译进去，刚刚试着编译了一下有几个文件和ssr+冲突了所以导致编译失败，涉及到的文件：
> `/etc/china_ssr.txt /etc/config/black.list /etc/config/gfw.list /etc/config/white.list /etc/dnsmasq.oversea/oversea_list.conf /etc/dnsmasq.ssr/ad.conf /etc/dnsmasq.ssr/gfw_base.conf`

SSR+ 和 passwall不能共存，这里有Lienol的回复https://github.com/Lienol/openwrt-package/issues/54#issuecomment-562859266

**Comment by EnnawYang** [comment]
> > 建议文件内容再稍微修改下，可以与lean或者其他人的共存，比如passwall可以和ssr+共存，同时编译进去，刚刚试着编译了一下有几个文件和ssr+冲突了所以导致编译失败，涉及到的文件：
> > `/etc/china_ssr.txt /etc/config/black.list /etc/config/gfw.list /etc/config/white.list /etc/dnsmasq.oversea/oversea_list.conf /etc/dnsmasq.ssr/ad.conf /etc/dnsmasq.ssr/gfw_base.conf`
> 
> SSR+ 和 passwall不能共存，这里有Lienol的回复[Lienol/openwrt-package#54 (comment)](https://github.com/Lienol/openwrt-package/issues/54#issuecomment-562859266)

这个issue是依赖包重复，去重后可以顺利编译，我自己编译的就是共存的

**Comment by norikohxb** [comment]
如何去掉依赖包重复？能否赐教？
