### ISSUE TITLE
重启后问题

### ISSUE THREAD

**Issue by lfm09** [jerrykuku/luci-app-vssr#55]
已有所好转

**Comment by lfm09** [comment]
@jerrykuku 刚刚试了一下最新版，依然有这个问题。本来好好的，切换了一个节点后也使用正常，然后关路由，再开机就上不了网了。这问题太折腾人了，还请老大尽快修正一下啊~

**Comment by lfm09** [comment]
今天又碰到冷重启后无法上本土网站的问题，抓狂，无奈放弃

**Comment by jerrykuku** [comment]
问题是为什么总要冷重启

**Comment by lfm09** [comment]
@jerrykuku 很正常啊，白天外出关掉，晚上再开。

**Comment by lfm09** [comment]
@jerrykuku 很正常啊，白天外出关掉，晚上再开。

**Comment by lfm09** [comment]
@jerrykuku 很正常啊，白天外出关掉，晚上再开。

**Comment by lfm09** [comment]
@jerrykuku 发现一个问题，虽然本插件的自启动脚本设置的优先级是START=90，软链接也是S90，但是“系统->启动项”中显示的启动优先级却是2。怀疑路由重启无法上网的问题是否与本插件过早启动有关？麻烦老大看看

**Comment by jerrykuku** [comment]
这个问题过了这么久，才重新发现，这个确实是我的失误，新的版本应该已经修复了此问题，欢迎更新。
