### ISSUE TITLE
[功能请求]细化规则设定，简化黑白名单添加

### ISSUE THREAD

**Issue by tofuliang** [jerrykuku/luci-app-vssr#7]
虽然现在很多人都在diss koolshare 的固件，但无可否认，koolshare有做得人性化的地方，例如可以针对IP或者MAC进行规则设定，
<img width="1621" alt="Jietu20200127-164857" src="https://user-images.githubusercontent.com/1814685/73161146-cef54f80-4125-11ea-8472-244d1f95a3d2.png">
快捷地设定黑白名单
<img width="1602" alt="Jietu20200127-165015" src="https://user-images.githubusercontent.com/1814685/73161154-d3ba0380-4125-11ea-9ee5-a1ce5ed2a57d.png">

目前该插件已经停止开发 了，不过在这里能找到[存档](https://github.com/myteer/ledesoft/blob/5561907d28/v2ray/history/2.3.7/v2ray.tar.gz)

**Comment by fengqi** [comment]
这个针对ip确实方便
