### ISSUE TITLE
开启分流，台湾视频服务代理没有下拉菜单

### ISSUE THREAD

**Issue by lumaode** [jerrykuku/luci-app-vssr#73]
![2020-10-29_19-54-22](https://user-images.githubusercontent.com/7458643/97566085-43488080-1a21-11eb-9447-a0583f7536ba.png)

**Comment by jerrykuku** [comment]
因为台湾分流，需要节点类型为台湾地区，如果订阅的时候没有正确识别为台湾地区的话，自己手动编辑一下节点，区域改成tw

**Comment by lumaode** [comment]
如你所说，手动修改节点 flag 参数，问题解决。
