### ISSUE TITLE
节点列表页面，点击节点修改按钮，LUCI崩溃

### ISSUE THREAD

**Issue by Hw0fz6kW** [jerrykuku/luci-app-vssr#76]
1.节点列表页面，点击节点修改按钮，LUCI崩溃
![2020-11-04_22-51-39](https://user-images.githubusercontent.com/7458643/98127513-c110fe00-1ef1-11eb-910e-19ca3f340d3f.png)
![2020-11-04_22-52-19](https://user-images.githubusercontent.com/7458643/98127537-ca9a6600-1ef1-11eb-8352-aa19fe32a402.png)
![2020-11-04_23-03-36](https://user-images.githubusercontent.com/7458643/98127757-059c9980-1ef2-11eb-9e08-e7bc11f2dbef.png)
固件基于 lean openwrt 添加 luci-ap-vssr 编译。

2.应用按钮前面的图标无法显示

**Comment by fryderykhuang** [comment]
我也是一样的问题，86ea7e17419220576ba6c1fda501221da021c53a

**Comment by jerrykuku** [comment]
明天修复

**Comment by doney0318** [comment]
我也是这个问题，点了修改节点就报错，单独添加节点也是报错，错误信息

/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute arcombine dispatcher target for entry '/admin/services/vssr/servers/cfg064a8f'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:1322: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by jerrykuku** [comment]
https://github.com/jerrykuku/luci-app-vssr/commit/f9f2eca39a61895150fa135b2ac975ff6a8a8de1
问题已经修复

**Comment by Hw0fz6kW** [comment]
强迫症修复图标  luasrc/view/vssr/tblsection.htm 32行 icon-ok 改为 icon-use

![2020-11-05_15-05-51](https://user-images.githubusercontent.com/7458643/98208595-78e8ee80-1f78-11eb-80f3-a00068907c8a.png)

**Comment by houandy** [comment]
建议增加节点批量管理功能，一键删除ping不通的节点，或者ping值较高的节点。

**Comment by Ifover** [comment]
留个Tip. 点击按钮报这个错误, 可能是因为开启了自动分页脚本
