### ISSUE TITLE
v1.18 版本 WARNING: Makefile 'package/lean/luci-app-vssr/Makefile' has a dependency on 'xray', which does not exist

### ISSUE THREAD

**Issue by zijun726911** [jerrykuku/luci-app-vssr#86]
v1.18 版本 输入  make menuconfig 的时候提示：

`WARNING: Makefile 'package/lean/luci-app-vssr/Makefile' has a dependency on 'xray', which does not exist`

之后 `make -j1 V=s` 编译不成功

**Comment by jerrykuku** [comment]
请添加xray 源码

**Comment by wangweitung** [comment]
> 
> 
> 请添加xray 源码

这个要怎么加？
能否写的详细点？
小白确实不会。

**Comment by zijun726911** [comment]
cd lede/package/lean  
git clone xray的代码（具体是哪个我忘了，可能不是这个https://github.com/yichya/luci-app-xray.git）
cd ../..
make menuconfig （生成配置文件选中xray）
make （编译）

**Comment by wangweitung** [comment]
> 
> 
> cd lede/package/lean
> git clone xray的代码（具体是哪个我忘了，可能不是这个[https://github.com/yichya/luci-app-xray.git）](https://github.com/yichya/luci-app-xray.git%EF%BC%89)
> cd ../..
> make menuconfig （生成配置文件选中xray）
> make （编译）

感谢大佬，确实可用。分享下我的命令如下：

~~~
cd /lede/package/lean
svn checkout https://github.com/jerrykuku/lua-maxminddb/trunk lua-maxminddb
svn checkout https://github.com/jerrykuku/luci-app-vssr/trunk luci-app-vssr
git clone https://github.com/yichya/luci-app-xray.git
cd /lede
git pull
./scripts/feeds update -a && ./scripts/feeds install -a
make menuconfig
make -j5 V=s
~~~

**Comment by wangweitung** [comment]
今天再编译，怎么又多了一个：
WARNING: Makefile 'package/lean/luci-app-vssr/Makefile' has a dependency on 'xray-plugin', which does not exist

又缺了那个包？

**Comment by wangweitung** [comment]
> 
> 
> 今天再编译，怎么又多了一个：
> WARNING: Makefile 'package/lean/luci-app-vssr/Makefile' has a dependency on 'xray-plugin', which does not exist
> 
> 又缺了那个包？

https://github.com/kenzok8/small
这里基本是全的，v2ray-core要另外下载


解决了
