### ISSUE TITLE
VSSR无法显示节点地区的国旗图标

### ISSUE THREAD

**Issue by gb5255** [jerrykuku/luci-app-vssr#88]
openwrt安装了最新的VSS的，但无法正确显示节点地区的国旗图标，请问是哪里出了什么问题？

**Comment by jerrykuku** [comment]
哪个位置不能显示 是底部 还是节点列表？

**Comment by gb5255** [comment]
底部无法显示 只能显示出IP地址，然后地区显示Unkown  并不能显示地址国旗

**Comment by jerrykuku** [comment]
你安装的哪个版本？

**Comment by gb5255** [comment]
最新版的luci-app-vssr_1.17-1-20200830_all

**Comment by jerrykuku** [comment]
你是不是少安装了 lua-maxminddb 这个依赖？

**Comment by gb5255** [comment]
我忽略了，感谢提醒！
