### ISSUE TITLE
添加节点后报错

### ISSUE THREAD

**Issue by j999yp** [jerrykuku/luci-app-vssr#89]
添加V2ray节点并保存后无法进入基本设置，报错如下
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/vssr/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/vssr/client.lua:31: bad argument #3 to '?' (no value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by jerrykuku** [comment]
哪个版本呢？

**Comment by j999yp** [comment]
> 哪个版本呢？

原本在恩山下载的固件里是1.17，也有同样的问题，手动下载ipk更新到1.20仍没有解决

**Comment by jerrykuku** [comment]
方便给我一个节点信息的例子么？ 不一定是要真的信息，只要你测试出来这样填写就会出错的即可。谢谢

**Comment by j999yp** [comment]
> 方便给我一个节点信息的例子么？ 不一定是要真的信息，只要你测试出来这样填写就会出错的即可。谢谢
![1](https://user-images.githubusercontent.com/38547892/101453589-8bd15300-396a-11eb-98a7-3a7d1ae88ce3.png)

**Comment by jerrykuku** [comment]
你尝试添加一个别名试试看

**Comment by j999yp** [comment]
> 你尝试添加一个别名试试看

这次没有报错，但是之前添加别名也会报错，不知道是什么原因？

**Comment by jerrykuku** [comment]
下次我修复不添加别名出错的问题

**Comment by j999yp** [comment]
> 下次我修复不添加别名出错的问题

感谢大佬的辛勤付出
